basePath: /api/v1
definitions:
  models.Article:
    properties:
      content:
        type: string
      created_by:
        type: string
      created_on:
        type: integer
      desc:
        type: string
      id:
        type: integer
      modified_by:
        type: string
      modified_on:
        type: integer
      state:
        type: integer
      tag:
        $ref: '#/definitions/models.Tag'
      tag_id:
        type: integer
      title:
        type: string
    type: object
  models.Tag:
    properties:
      created_by:
        type: string
      created_on:
        type: integer
      id:
        type: integer
      modified_by:
        type: string
      modified_on:
        type: integer
      name:
        type: string
      state:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: myweb API docs
  version: "1.0"
paths:
  /articles:
    get:
      description: 获取所有的文章
      parameters:
      - description: 文章id
        in: query
        name: id
        type: string
      responses:
        "200":
          description: desc
          schema:
            items:
              $ref: '#/definitions/models.Article'
            type: array
        "400":
          description: '{"msg": "who are you"}'
          schema:
            type: string
      summary: 获取所有文章
      tags:
      - 文章
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
